on:
  - pull_request
  - push
  - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build setup-watcom
        run: |
          ./build.sh
          mv packed/index.js index.js
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: action-artifact
          if-no-files-found: error
          path: |
            index.js

  test-2_0:
    name: "OpenWatcom 2.0 on ${{ matrix.runner }}"
    needs: build
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: action-artifact
      - name: "Run action"
        run: |
          node index.js
        env:
          INPUT_VERSION: "2.0"
          INPUT_TAG: ""
          INPUT_LOCATION: ""
          INPUT_ENVIRONMENT: "true"
      - name: Use watcom
        run: |
          wcl -h
          wcl386 -h

  test-1_9:
    name: "OpenWatcom 1.9 on ${{ matrix.runner }}"
    needs: build
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: action-artifact
      - name: "Run action"
        run: |
          node index.js
        env:
          INPUT_VERSION: "1.9"
          INPUT_TAG: ""
          INPUT_LOCATION: ""
          INPUT_ENVIRONMENT: "true"
      - name: Use watcom
        run: |
          wcl -h
          wcl386 -h
